services:
  v5notes-admin:
    container_name: v5notes-admin
    ports:
      - 8080:8080
    volumes:
      - /mnt/v5notes/config/:/v5notes/server/config/
    image: onedev.v5ai.xin/v5notes/v5notes-admin:latest
    networks:
      - v5notes-net

networks:
  v5notes-net:
    driver: bridge
